{% set name = "fastapi-restful" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi_restful-{{ version }}.tar.gz
  sha256: 302d0f8404b3c868b3e813b36316cf29084b6b1c82e4f21ce57405d955104a43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7
    - fastapi >=0.89,<1.0
    - pydantic >=1.0,<2.0
    - psutil >=5.0.0,<6.0
  run_constrained:
    - sqlalchemy >=1.4.0,<2.0.0

test:
  imports:
    - fastapi_restful
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yuval9313/FastApi-RESTful
  summary: Quicker FastApi developing tools
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yuval9313/FastApi-RESTful
  doc_url: https://fastapi-restful.netlify.app

extra:
  recipe-maintainers:
    - pavelzw
